#!/bin/bash
# 02-edpm-cinder-patch.sh
#
# Run this script as root on each EDPM node.
# Run AFTER 01-ocp-cinder-patch.sh has generated lightos-patched.py.
# If no path to the patched lightos.py is supplied, the current directory is used.
#
# Usage: ./02-edpm-cinder-patch.sh [path-to-lightos-patched.py]
# Example: ./02-edpm-cinder-patch.sh /tmp/lightos-patched.py

set -euo pipefail

LIGHTOS_PY="${1:-$(pwd)/lightos-patched.py}"

echo "=== [2/3] Lightbits Cinder patch for EDPM node ==="

# Check prerequisites
if ! command -v sed &>/dev/null; then
  echo "ERROR: sed not found in PATH"
  exit 1
fi

# Validate the patched file exists
if [ ! -f "$LIGHTOS_PY" ]; then
  echo "ERROR: Patched lightos.py not found at: $LIGHTOS_PY"
  echo "Usage: $0 [path-to-lightos-patched.py]"
  exit 1
fi

# Validate it contains the host_ips patch
if ! grep -q "host_ips" "$LIGHTOS_PY"; then
  echo "ERROR: $LIGHTOS_PY does not contain the host_ips patch."
  echo "Make sure you are using the file generated by 01-ocp-cinder-patch.sh"
  exit 1
fi

echo "Using patched file: $LIGHTOS_PY"

# Step 1: Install patched lightos.py
echo ""
echo "[1/2] Installing patched lightos.py to /etc/lightbits-nova-lightos.py..."
cp "$LIGHTOS_PY" /etc/lightbits-nova-lightos.py
chmod 644 /etc/lightbits-nova-lightos.py
echo "Done"

# Step 2: Create /etc/node-hostname
echo ""
echo "[2/2] Creating /etc/node-hostname..."
hostname > /etc/node-hostname
echo "Node hostname set to: $(cat /etc/node-hostname)"

echo ""
echo "=== EDPM node patch complete ==="
echo ""
echo "Run this script on all remaining EDPM nodes, then run"
echo "03-ocp-edpm-nova-patch.sh from your OCP client."
