#!/bin/bash

readonly INSTANCE_TYPE=r6in.4xlarge
# RHEL8.x (Amazon) - ami-092b43193629811af
# Alma8.x (Amazon) - ami-09e57b4a97b8f8b10
readonly KEY_NAME=the_name_of_your_stored_aws_key
readonly IMAGE_ID=pick_one_from_above_or_use_yours
readonly SUBNET_ID=the_subnet_id_for_the_new_instance
readonly SECURITY_GROUP=the_securty_group_id_for_the_new_instance
readonly ROOT_VOLUME_TYPE=gp3
readonly ROOT_VOLUME_SIZE=85
readonly INSTANCE_NAME=oracle
readonly NUMBER_OF_INSTANCES=1
readonly HOST_FILE=oracle_clients
# Leave PLACEMENT_GROUP empty ("") to use without a placement group
readonly PLACEMENT_GROUP=the_placment_group_name_that_was_created_with_the_lighbits_cluster

if [[ ${PLACEMENT_GROUP} == "" ]]; then
  placement_command=""
  echo "Creating EC2 instance without a placement group..."
else
  placement_command="--placement GroupName=${PLACEMENT_GROUP}"
  echo "Creating EC2 instance within placement group ${PLACEMENT_GROUP}"
fi

[[ -e ${HOST_FILE} ]] && rm -f ${HOST_FILE}

for ((x=1;x<=NUMBER_OF_INSTANCES;x++))
do
  cli_output=$(aws --profile lb-perf ec2 run-instances \
    --no-cli-pager \
    --count 1 \
    --instance-type ${INSTANCE_TYPE} \
    --key-name ${KEY_NAME} \
    --image-id ${IMAGE_ID} \
    --subnet-id ${SUBNET_ID} \
    --security-group-ids ${SECURITY_GROUP} \
    --associate-public-ip-address \
    ${placement_command} \
    --output json \
    --block-device-mappings 'DeviceName=/dev/sda1,Ebs={VolumeSize='${ROOT_VOLUME_SIZE}',VolumeType='${ROOT_VOLUME_TYPE}',DeleteOnTermination=true}' \
    --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value='${INSTANCE_NAME}${x}'}]' | jq -rc '.Instances[] | "\(.PrivateDnsName),\(.State.Name)"')
  aws_instance_name=$(echo ${cli_output} | awk -F, '{print $1}')
  aws_instance_status=$(echo ${cli_output} | awk -F, '{print $2}')
if [[ "${aws_instance_status}" == "pending" ]]; then
  echo "${aws_instance_name} is pending, adding it to pssh host file ${HOST_FILE}..."
  echo ${aws_instance_name} >> ${HOST_FILE}
fi
done
